# Generated by Django 5.0.4 on 2024-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
